---
title: "Centrality scores"
subtitle: "Authors' centrality scores in co-authorship networks!"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: spacelab
    source_code: embed
    fontsize: 16pt
---

```{js, echo = FALSE, message = FALSE, warning = FALSE}
function filter_default() {
    document.getElementById("GENDER").getElementsByClassName("selectized") 
[0].selectize.setValue("both", false);
 }
$(document).ready(filter_default);
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(plotly)
library(crosstalk)

library(htmltools)
library(dplyr)

myfont="Times New Roman"
knitr::opts_chunk$set(echo = FALSE)


centralities<-read.table("centralities.csv",header=TRUE,sep=";",quote="\r",dec = ".")
sharedCentrality<-SharedData$new(centralities)

p_degree<-ggplot(sharedCentrality, aes(x=YEAR-1999, y=score_mean, group=MOBILITY, color=MOBILITY)) + 
  geom_line(size=0.7) +
  geom_point(shape=21, size=0.1, fill="red") +
  geom_errorbar(aes(ymin=score_mean -score_se , ymax=score_mean+score_se ), width=0.25,colour="red",
               position=position_dodge(0.001), alpha=0.7)+
  labs( x="Career age", y = "Score")+
  #theme_classic()+
  theme_bw()+
  theme(legend.position = "top",legend.title=element_blank(),legend.text=element_text(family=myfont,size="12",face="bold")
        ,axis.text  =  element_text( family=myfont,size=12),axis.title  =  element_text( family=myfont,size=16,face = "bold"),plot.margin = margin(1,1,1.5,1.2, "cm"),panel.spacing = unit(4, "lines"))+
  scale_color_manual(values=c('#0000FF','#808080'))+
  facet_wrap( ~ score, ncol=2, scales = "free")+ labs(color = "")

gg_degree<-ggplotly(p_degree)



bscols(widths = c(2,2,12,12),
       div(style = css(width="2%", height="2px", background_color="gray")),
       list(
         filter_select(id = "GENDER", label = "Gender",
                       sharedData = sharedCentrality, group = ~ GENDER,multiple=FALSE,allLevels = FALSE)
       ),div(style = css(width="100%", height="2px", background_color="gray")),
       gg_degree)
  
  





```

This figure compares four centrality measures of mobile and non-mobile researchers in collaboration networks during their career development. The numbers of observations are 18,734 and 29,122 for mobile and non-mobile researchers, resp. Red error bars show standard errors. X-axes show the Career age, which ranges from 1 to 16 years (year of first publication and 15 years after that), and y-axes the related centrality score. Using the filter, results of a specific gender can be displayed.

Comparing the centrality of mobile and non-mobile researchers in the co-authorship networks displays the position and role of mobile researchers in these networks.
For mobile researchers, we observe a growing trend in degree and coreness by increasing the career age. These two observations suggest that not only mobility increases the social capital of the scholars (degree), but also it helps to position the scholars into the core of the community which would allow
them to get better access to highly influential people. In contrast, the lower clustering coefficient of mobile researchers indicates that by increasing
their degree, they diversify their co-authors and belong to various communities and thus they
act more as bridges between the communities. 

For more information about the definition of centrality scores , please see the <a href="https://doi.org/10.1016/j.joi.2022.101280">paper, section 3.6</a>. 

   
