project:
  type: website

website:
  title: "OASE/OAUNI Dashboard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "Publications"
        href: pubs.qmd
        
  sidebar: 
    - title: "Home"
    - title: "About"
      style: "docked"
      contents:
        - about.qmd
        - oase.qmd
        - oauni.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

