project:
  type: website
  output-dir: docs

website:
  title: "OASE/OAUNI Dashboard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Mobility"
        href: mobility.qmd
      - text: "OA Nature"
        href: oa_nature.qmd
    right:
      - text: "Publications"
        href: pubs.qmd
        
  sidebar: 
    - title: "Home"
    - title: "About"
      style: "docked"
      contents:
        - about.qmd
        - oauni.qmd
        - oase.qmd
    - title: "Mobility"
      style: "docked"
      contents: 
        - mobility.qmd
        - International-Academic-Mobility/mobility_proportion_filed_gender.Rmd
        - International-Academic-Mobility/mobility_score_distribution.Rmd
        - International-Academic-Mobility/country_gender_field.Rmd
        - International-Academic-Mobility/mobility_flow.Rmd
        - International-Academic-Mobility/centrality.Rmd
    - title: "OA Nature"
      style: "docked"
      contents: 
        - oa_nature.qmd
        - Springer_Nature-Open_Access/journals_model.Rmd
        - Springer_Nature-Open_Access/model_income.Rmd
        - Springer_Nature-Open_Access/hybrid_model_income.Rmd
        - Springer_Nature-Open_Access/citation.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

