---
title: "OASE"
editor: visual
---

The project **Open Access-Effekte ([OASE](https://www.wihoforschung.de/wihoforschung/en/bmbf-funding-projects/funding-lines/quantitative-research-on-the-science-sector/oase/oase.html)) - Strukturelle und autorspezifische Einflussfaktoren auf die Qualität und Impact von QA-Publikationen** describes the transformation process from traditional to OA publishing with a bibliometric approach and analyzes existing (if applicable future) publishing strategies and conflicts in the context of OA.

The project studies systematically, longitudinally and comprehensively the structural and author specific influencing factors of OA impact in the social sciences, economics and selected sciences. Traditional and altmetric indicators will test the validity of popular thesis on OA. We focus on most relevant thesis and influencing factors which are discussed in the literature and seek to validate the thesis, quantify the effects, show the causal associations and answer novel problems. We ask: wherein exists the "genuine" OA effect (e.g. increased citation and altmetric rates via accessibility)? In which extent appears the OA effect in difference constellations (combination of structural and author specific properties)?

The study bases on articles from the Web of Science databases. These articles will be aggregated differently for the three work packages, e.g. on the author level, and will be analyzed in a bibliometric and altmetric way. In addition, we will perform quantitative surveys, interviews and workshops with authors who have published in OA and/or cited/shared OA to validate the results from the bibliometrics and altmetric studies and to gain deeper insights in the discipline specific OA publishing and OA citing behavior. These insights will flow into a model of transdisciplinary and discipline specific influencing factors. The three work packages divide into structural (WP1) and author specific properties of OA publications (WP2), author surveys (WP3) and assume in a report of the OASE "lessons learned".
