---
title: "General Info"
subtitle: "on the study “Development and Typology of the Data Service Unpaywall“"
editor: visual
---

The article has been published in [Bibliothek Forschung und Praxis](https://www.degruyter.com/document/doi/10.1515/bfp-2020-0115/html).

## Abstract

Analyses in the field of open access publishing have become significantly easier with the availability
of large connected data collections such as Unpaywall. The article examines the development of the database
and its structure since 2018. A full survey of journal articles from the period 2008–2018 shows that the OA
share is growing continuously. However, the OA categorisation varies, which raises methodological questions
in publication monitoring and bibliometric research.

## Snapshot Info

The following table shows a general overview of changes in Unpaywall snapshots. For each snapshot, the columns contain information on the indexed publications (here limited to journal articles), information on the OA share, information on the ratio of publications via publishers and repositories (only publications with the attribute is_best=True were taken into account here), innovations in the data schema and a statistical evaluation of the evidence types.

| Snapshot | Number of Articles | Open Access Share| Repositories/ Publisher Share | Schema modifications | Number of Evidence types |
|--------------|-----------|------------|--------------|-----------|------------|
| March 2018 Snapshot | 27.498.666 | 31,56% | 21,45%/78,55% | | 22 |
| April 2018 Snapshot | 27.268.179 | 32,58% | 19,80%/80,20% | | 22 |
| June 2018 Snapshot | 28.201.468 | 35,55% | 19,17%/80,83% | x_reported_noncompliant_copies removed | 23 |
| September 2018 Snapshot | 29.908.032 | 37,86% | 17,21%/82,79% | | 15 |
| February 2019 Snapshot | 31.159.960 | 37,34% | 17,97%/82,03% | endpoint_id added | 15 |
| April 2019 Snapshot | 31.341.794 | 38,11% | 17,68%/82,32% | oa_status added | 17 |
| August 2019 Snapshot | 31.602.128 | 38,75% | 17,23%/82,77% | journal_issn_l and repository_institution added | 19 |
| November 2019 Snapshot | 31.827.129 | 42,63% | 26,52%/73,48% | has_repository_copy added | 18 |
| February 2020 Snapshot | 31.611.299 | 42,79% | 22,76%/77,24% | is_paratext added | 17 |
| April 2020 Snapshot | 31.482.103 | 42,50% | 23,22%/76,78% | | 18 |

: Summary of Changes in Unpaywall snapshots
